# Generated by Django 4.2 on 2023-04-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whack_blob', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescore',
            options={'ordering': ['-score']},
        ),
    ]
