# Generated by Django 4.2 on 2023-04-18 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whack_blob', '0002_alter_gamescore_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_game', to=settings.AUTH_USER_MODEL),
        ),
    ]
