# Generated by Django 4.2 on 2023-04-20 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whack_blob', '0005_alter_gamescore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamescore',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
