# Generated by Django 4.2 on 2023-04-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whack_blob', '0006_gamescore_created_at_gamescore_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescore',
            options={'ordering': ('-created_at',)},
        ),
    ]
