# Generated by Django 4.2 on 2023-04-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whack_blob', '0008_referral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
